// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApplication = "applications"

// Application mapped from table <applications>
type Application struct {
	AppID     int32     `gorm:"column:app_id;primaryKey;autoIncrement:true" json:"app_id"`            // Application ID
	AppName   string    `gorm:"column:app_name;not null" json:"app_name"`                             // Application name
	AppStatus string    `gorm:"column:app_status;not null;default:development" json:"app_status"`     // Application status
	AppPort   int32     `gorm:"column:app_port;not null" json:"app_port"`                             // Application docker image port
	AppImage  string    `gorm:"column:app_image;not null" json:"app_image"`                           // Application docker image URL
	DockerID  string    `gorm:"column:docker_id;not null" json:"docker_id"`                           // Application docker image ID
	UserID    int32     `gorm:"column:user_id;not null" json:"user_id"`                               // User ID
	IsDeleted bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`                         // Is deleted
	CreateAt  time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"` // Create time
	UpdateAt  time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"` // Update time
}

// TableName Application's table name
func (*Application) TableName() string {
	return TableNameApplication
}
