// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID    int32     `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`          // User ID
	UserName  string    `gorm:"column:user_name;not null" json:"user_name"`                           // Username
	Email     string    `gorm:"column:email;not null" json:"email"`                                   // Email
	Password  string    `gorm:"column:password;not null" json:"password"`                             // Password
	Avatar    string    `gorm:"column:avatar" json:"avatar"`                                          // Avatar
	IsActive  bool      `gorm:"column:is_active;not null" json:"is_active"`                           // Is active
	IsAdmin   bool      `gorm:"column:is_admin;not null" json:"is_admin"`                             // Is admin
	IsDeleted bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`                         // Is deleted
	CreateAt  time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"` // Create time
	UpdateAt  time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"` // Update time
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
